#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GLNLabelPrint.Resource", IsApplication=true)]

namespace GLNLabelPrint
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::GLNLabelPrint.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::GLNLabelPrint.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::GLNLabelPrint.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::GLNLabelPrint.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::GLNLabelPrint.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::GLNLabelPrint.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::GLNLabelPrint.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::GLNLabelPrint.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::GLNLabelPrint.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::GLNLabelPrint.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::GLNLabelPrint.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::GLNLabelPrint.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::GLNLabelPrint.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::GLNLabelPrint.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::GLNLabelPrint.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::GLNLabelPrint.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::GLNLabelPrint.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::GLNLabelPrint.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::GLNLabelPrint.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::GLNLabelPrint.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::GLNLabelPrint.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::GLNLabelPrint.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::GLNLabelPrint.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::GLNLabelPrint.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::GLNLabelPrint.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::GLNLabelPrint.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int quantity_array = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int valid_devices = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int ahBarColor = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int ahBarLength = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int ahBarWidth = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int ahCircleColor = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int ahDelayMillis = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int ahRadius = 2130771981;
			
			// aapt resource value: 0x7f010008
			public const int ahRimColor = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int ahRimWidth = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int ahSpinSpeed = 2130771978;
			
			// aapt resource value: 0x7f010004
			public const int ahText = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahTextColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahTextSize = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int dark_gray = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int androidIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dakota_healthcare_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dakota_healthcare_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dakota_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_errorstatus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_successstatus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int list_selector_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int roundedbg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int roundedbgdark = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001a
			public const int About = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int FindPrinters = 2131034134;
			
			// aapt resource value: 0x7f05000b
			public const int ListItemRowText = 2131034123;
			
			// aapt resource value: 0x7f050017
			public const int LoadDataFile = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int LoadFile = 2131034133;
			
			// aapt resource value: 0x7f050010
			public const int PrintButton = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int PrintQuantity = 2131034132;
			
			// aapt resource value: 0x7f05001b
			public const int Quit = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int SelectAllLocations = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int SelectNoLocations = 2131034137;
			
			// aapt resource value: 0x7f050002
			public const int aboutAppname = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int aboutLogo = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int aboutText = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int aboutVersion = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int buttonOK = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int buttonSearch = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int editTextSearch = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int fileListView = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int loadingImage = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int loadingProgressBar = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int loadingProgressWheel = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int locationsView = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int printerListView = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int selectedPrinterTxt = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int simpleCheckedListItem = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int spinnerQty = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int textViewStatus = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutBox = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CheckedListRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FindFiles = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FindLocation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FindPrinters = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loading = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingimage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loadingprogress = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PrintQuantity = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int dialog = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int popup_menu = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int About = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int AboutBox = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int AboutBoxText = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int AppName = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int ApplicationName = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int Discovered = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int Find = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int FindFiles = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int FindPrinters = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int Hello = 2131099673;
			
			// aapt resource value: 0x7f060009
			public const int LoadDataFile = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int LoadLocations = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int NoPrinter = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int Print = 2131099652;
			
			// aapt resource value: 0x7f060015
			public const int PrintQuantity = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int Quantity_prompt = 2131099672;
			
			// aapt resource value: 0x7f060003
			public const int Quit = 2131099651;
			
			// aapt resource value: 0x7f060016
			public const int QuitApplication = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int QuitPrompt = 2131099671;
			
			// aapt resource value: 0x7f06000c
			public const int RowInfo = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int SearchLocation = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int SearchPrinters = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int SelectAllLocations = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int SelectNoLocations = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int Version = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int app_light = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int dialog_light = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
